[workspace]

members = [
    "lsh-rs",
    "lsh-rs/bench",
    "lsh-py",
    "examples/reverse-img-search",
    "examples/reverse-img-search/bench",
    "examples/neural-network",
    "lsh-rs/floky-bin"
]

[profile.release]
codegen-units = 1
target-cpu = "native"
lto = "fat"
